# Generated by Django 4.2.3 on 2023-07-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competitions',
            new_name='Competition',
        ),
        migrations.RenameIndex(
            model_name='competition',
            new_name='drones_comp_distanc_540c76_idx',
            old_name='drones_comp_distanc_b75f0c_idx',
        ),
    ]
