# Generated by Django 4.2.3 on 2023-07-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_rename_competitions_competition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='dronecategory',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
